# Generated by Django 4.0.10 on 2023-12-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('imap_server', models.CharField(max_length=255)),
            ],
        ),
    ]
